Update CHECKLIST.md
GuillaumeDesforges/nix-survey pull request #13
Opened 2024-11-03 13:48 UTC by fricklerhandwerk

Add a few notes based on the feedback question

2024-11-03 13:53 UTC, GuillaumeDesforges requested changes

2024-11-03 13:53 UTC, GuillaumeDesforges commented on 2025/CHECKLIST.md
> +        - always add "other" field to selections
I'm strongly against it. It circles back to open-ended questions being costly and hard to analyze.

IMO one of the reasons we could make the most of the survey in 2024 was that we put more thought in the question prompt and answer choices. If anything is missing, it should be added to everybody.

If people feel a question needed an "Other" field, we need to work on the question.

```suggestion
```

2024-11-03 16:29 UTC, fricklerhandwerk commented on 2025/CHECKLIST.md
> +        - always add "other" field to selections
Hmmm. The problem is that things like "which language ecosystem do you use" will always have some outliers missing and leave some people with the feeling of not being represented. I think it's fine to aggregate those one-liner things programmatically; the data cleaning on those should be fairly easy.

Having the known most common options hard coded will capture the bulk of the answers already, so we'll always have a good sample to start with.

2024-11-04 22:14 UTC, GuillaumeDesforges commented on 2025/CHECKLIST.md
> +        - always add "other" field to selections
I still think that many people will prefer using the "other" choice to input a choice that would usually fall into one of the provided category. While I agree that it is important to be welcoming and inclusive, I think it is our responsibility to provide usable data as well.

Now, that's not a hill I will die on. IMO, it's up to whomever does the job to do it however they want. But I would not feel comfortable forcing this onto anyone taking over me if there was.

2024-11-04 22:16 UTC, merged